# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: installer
  inputs:
    version: 2.1.505

- task: Npm@1
  displayName:  run npm install
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: compile sccs

- task: Gulp@1
  displayName: Run gulp tasks

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@1
  displayName: Restore settings
  inputs: 
   command: restore
   projects: '**/*.csproj'

- task: SonarCloudPrepare@1
  displayName: Sonar Analysis
  inputs:
      SonarCloud: 'Sonarcloud'
      organization: '$(sonarorgname)'
      projectKey: $(projectkey)
      projectName: $(projectkey)
      projectVersion: $(Build.BuildNumber)
      extraProperties: |
       sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/TestResults/Coverage/coverage.opencover.xml
       sonar.exclusions=**/wwwroot/lib/**/*
- task: DotNetCoreCLI@2
  displayName: Build the project
  inputs:
    command: build
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Execute Unit Test
  inputs:
    command: test
    arguments: '--no-build --configuration $(BuildConfiguration)'
    publishTestResults: true
    projects: '**/*.Test.csproj'

- task: DotNetCoreCLI@2
  displayName: Publish project
  inputs:
    command: publish
    arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/Release'
    zipAfterPublish: true

- task: SonarCloudAnalyze@1
  displayName: SonarAnalyser

- task: SonarCloudPublish@1
  displayName: Sonarpublish
  

- task: PublishBuildArtifacts@1
  displayName: Publish artifacts
  condition: succeeded()
